

//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#include "PCH_Contents.h"

#include "ContentsInitializer.h"
#include <Engine/Manager/ComponentManager.h>
#include "strKey_UserComponent.h"



#define CONSTRUCTOR_T(T) ComponentManager::AddComponentConstructor<T>(strKey::component::##T)

namespace ehw
{

	void ContentsInitializer::InitUserComponent()
	{
	}
}