

//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#include "PCH_Contents.h"

#include "ContentsInitializer.h"
#include <Engine/Manager/SceneManager.h>
#include "strKey_Scene.h"


#include "Scene\Scene_Title.h"

#define CONSTRUCTOR_T(T) SceneManager::AddSceneConstructor<T>(strKey::scene::##T)

namespace ehw
{

	void ContentsInitializer::InitScene()
	{
		CONSTRUCTOR_T(Scene_Title);
	}
}