

//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#include "PCH_UserContents.h"

#include "ContentsClassInitializer.h"
#include <EngineBase/Engine/ComMgr.h>
#include "strKey_Script.h"


#include "Script_CameraMove.h"
#include "Script_Player.h"

#define CONSTRUCTOR_T(T) ComMgr::AddComConstructor<T>(strKey::Script::##T)

namespace ehw
{
	using namespace ehw::define;
	void ContentsClassInitializer::InitScript()
	{
		CONSTRUCTOR_T(Script_CameraMove);
		CONSTRUCTOR_T(Script_Player);
	}
}