
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::strKey::component
{
}
