
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::define::strKey::Script
{
	STRKEY Script_CameraMove = "Script_CameraMove";
	STRKEY Script_Player = "Script_Player";
}
