
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::strKey::script
{
	STRKEY Script_CameraMove = "Script_CameraMove";
	STRKEY Script_Player = "Script_Player";
	STRKEY Script_Test = "Script_Test";
	STRKEY Script_Test2 = "Script_Test2";
}
