
#pragma once


//=========================================================
//This Code is Automatically generated by CodeGenerator.exe
//=========================================================


#ifndef STRKEY
#define STRKEY constexpr const char*
#endif



namespace ehw::strKey::Scene
{
	STRKEY Scene_Title = "Scene_Title";
}
