

//=========================================================
//This Code is Automatically generated by CodeGenerator
//=========================================================


#include "PCH_UserContents.h"

#include "UserContentsInitializer.h"
#include <Base/Engine/Manager/ComponentManager.h>
#include "strKey_UserComponent.h"



#define CONSTRUCTOR_T(T) ComponentManager::AddComponentConstructor<T>(strKey::component::##T)

namespace ehw
{

	void UserContentsInitializer::InitUserComponent()
	{
	}
}